### PR TITLE
on OSX, fixes the PHP warning using cli_set_process_title

### PR DESCRIPTION
**Pull request by AlexStef**
`Warning cli_set_process_title(): cli_set_process_title had an error: Not initialized correctly in vendor/chrisboulton/php-resque/lib/Resque/Worker.php on line 331`

### CODE REVIEW

**Comment by pitpit** [comment]
:+1:

**Comment by pitpit** [comment]
:+1:

**Comment by luishdez** [comment]
I sen't this one a few days ago https://github.com/chrisboulton/php-resque/pull/290/files I think it's better than using @ to silent all errors.

**Comment by pitpit** [comment]
hi,
what about merging this PR ?

**Comment by danhunsaker** [comment]
@pitpit #290 does this cleaner, so it's more likely to be merged.

@luishdez It still uses tabs because it has never tried to be PSR-2 compliant.  Also, it hasn't actually been updated in a few years, so there's that.

@AlexStef As @luishdez pointed out, you *will* need to preserve the existing coding style for future PRs to be merged...  That said, #290 is still cleaner, despite checking the specific platform.  Normally, I'd prefer your approach, but in this case...

**Comment by pitpit** [comment]
What about canceling coding style changes and keep the generic check of this PR instead of checking a specific OS ?

**Comment by danhunsaker** [comment]
@pitpit As I said, #290 does this cleaner. The use of `@` error suppression is never desirable, especially in production code. If a generic approach is submitted that *doesn't* use `@`, I'll happily back that one, but until then, a platform check is cleaner.

**Comment by pitpit** [comment]
Using a *@* to silent fatal error while catching and checking the result is not so bad in prod but your're the only captain on board ;)

**Comment by luishdez** [comment]
I agree with @danhunsaker. @ is not the best option for production.

In this PR you're silent all possible errors not only the OS X problem. So you won't be able to know what happens if another kind of problem occurs and won't be logged.

**Comment by chrisboulton** [comment]
Lets go with #290 for now - we'll reevaluate in the future and incorporate these changes if we need to. Thanks for the contribution!

**Pull request closed without merging**
