### PR TITLE
Added remove_queue command from Resque

### PR DESCRIPTION
**Pull request by drahmel**
Resque has the remove_queue command that removes the queue and all of the jobs. Added the method as removeQueue($queue) to php-resque.

### CODE REVIEW

**Comment by danhunsaker** [comment]
You'll probably want to clean out the whitespace changes.

**Comment by drahmel** [comment]
Done.

**Comment by danhunsaker** [comment]
Looks good from here.

There's a lot that Ruby's Resque has gained since this port was written that hasn't been ported across yet.  Good to see some of it trickling over.

**Comment by drahmel** [comment]
I noticed that the peek() command was also missing (something I use a lot on Beanstalk) but it is listed on the Resque cheatsheet (http://whatcodecraves.com/posts/2010/06/22/resque-cheatsheet.html). I want to find some time next week to take a shot at implementing that.

**Comment by danhunsaker** [comment]
Won't get any argument from me.  I'd love to see 100% parity between features and in-Redis content in this and the Ruby version.  If we can get the latest versions of each to interoperate with each other, that feels like a win. (This version interoperates with an older Ruby version just fine, so we just need to update for the changes since.)

**Comment by drahmel** [comment]
Any progress on this?

**Comment by danhunsaker** [comment]
@ChrisBoulton is pretty busy these days with other projects.  When he has enough time free to review this, I'm pretty sure it'll be merged.

**Comment by drahmel** [comment]
Thanks!

**Comment by chrisboulton** [comment]
Hi,

Sorry for the delay - yes, this seems useful. Thanks!

**Pull request merged**
