### PR TITLE
bin/resque 99行pid变量缺少一个$

### PR DESCRIPTION
**Pull request by sapolang**

### CODE REVIEW

**Comment by danhunsaker** [comment]
:+1:

This is an easy approve.  Pretty important bug to fix...  Though I'd recommend removing the `?>` at the end of the file...

**Comment by rajibahmed** [comment]
@danhunsaker I guess you are joking :) . PHP ending tags causes weird issues sometimes

**Comment by sapolang** [comment]
@rajibahmed we do not write the ?> at the end of file

**Comment by danhunsaker** [comment]
@rajibahmed - Huh?  I said *remove* it...

@sapolang - Indeed.  But you could remove it, since it's still there from earlier commits.

**Comment by rajibahmed** [comment]
I missed the pid variable fix.

**Comment by danhunsaker** [comment]
@rajibahmed - Ah, yeah.  Given that it was just PRed now, you're not the first.  :-D

**Pull request merged**
